version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: relayer-backend-app-dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - relayer-network
    restart: unless-stopped
    command: pnpm run start:dev

  redis:
    image: redis:7-alpine
    container_name: relayer-backend-redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redis_dev_data:/data
    networks:
      - relayer-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

volumes:
  redis_dev_data:
    driver: local

networks:
  relayer-network:
    driver: bridge
